server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
  datasource: 
    url: jdbc:h2:mem:flightreservations
  jpa:
    defer-datasource-initialization: true
  application:
    name: reservations

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      