server:
   port: 8084
   
spring:
   application:
      name: api-gateway
   cloud:
      gateway:
         routes:
            -  id: search
               uri: lb://search
               predicates:
                  -  Path=/airlines/**,/airports/**,/flights/**
            -  id: reservations
               uri: lb://reservations
               predicates:
                  -  Path=/bags/**,/passengers/**,/tickets/**
         globalcors:
            corsConfigurations:
               '[/**]':
                  allowedOrigins: "*"
                  allowedHeaders: "*"
                  allowedMethods: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka